chore(deps): update psutil requirement from <8,>=6.1 to >=7.2.2,<8 (#108)
Updates the requirements on
[psutil](https://github.com/giampaolo/psutil) to permit the latest
version.
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/giampaolo/psutil/blob/master/docs/changelog.rst">psutil's
changelog</a>.</em></p>
<blockquote>
<p>7.2.2 — 2026-01-28
^^^^^^^^^^^^^^^^^^</p>
<p><strong>Enhancements</strong></p>
<ul>
<li>:gh:<code>2705</code>: [Linux]: :meth:<code>Process.wait</code> now
uses <code>pidfd_open()</code> +
<code>poll()</code> (no busy loop). Requires Linux &gt;= 5.3 and Python
&gt;= 3.9.</li>
<li>:gh:<code>2705</code>: [macOS], [BSD]:
:meth:<code>Process.wait</code> now uses <code>kqueue()</code> (no
busy loop).</li>
</ul>
<p><strong>Bug fixes</strong></p>
<ul>
<li>:gh:<code>2701</code>, [macOS]: fix compilation error on macOS &lt;
10.7. (patch by
:user:<code>Sergey Fedorov &lt;barracuda156&gt;</code>)</li>
<li>:gh:<code>2707</code>, [macOS]: fix potential memory leaks in error
paths of
:meth:<code>Process.memory_full_info</code> and
:meth:<code>Process.threads</code>.</li>
<li>:gh:<code>2708</code>, [macOS]: :meth:<code>Process.cmdline</code>
and :meth:<code>Process.environ</code> may
fail with <code>OSError: [Errno 0] Undefined error</code> (from
<code>sysctl(KERN_PROCARGS2)</code>). They now raise
:exc:<code>AccessDenied</code> instead.</li>
</ul>
<p>7.2.1 — 2025-12-29
^^^^^^^^^^^^^^^^^^</p>
<p><strong>Bug fixes</strong></p>
<ul>
<li>:gh:<code>2699</code>, [FreeBSD], [NetBSD]:
:func:<code>heap_info</code> does not detect small
allocations (&lt;= 1K). In order to fix that, we now flush internal
jemalloc
cache before fetching the metrics.</li>
</ul>
<p>7.2.0 — 2025-12-23
^^^^^^^^^^^^^^^^^^</p>
<p><strong>Enhancements</strong></p>
<ul>
<li>:gh:<code>1275</code>: new :func:<code>heap_info</code> and
:func:<code>heap_trim</code> functions, providing
direct access to the platform's native C :term:<code>heap</code>
allocator (glibc,
mimalloc, libmalloc). Useful to create tools to detect memory
leaks.</li>
<li>:gh:<code>2403</code>, [Linux]: publish wheels for Linux musl.</li>
<li>:gh:<code>2680</code>: unit tests are no longer installed / part of
the distribution.
They now live under <code>tests/</code> instead of
<code>psutil/tests</code>.</li>
</ul>
<p><strong>Bug fixes</strong></p>
<ul>
<li>:gh:<code>2684</code>, [FreeBSD], [critical]: compilation fails on
FreeBSD 14 due to
missing include.</li>
<li>:gh:<code>2691</code>, [Windows]: fix memory leak in
:func:<code>net_if_stats</code> due to missing
<code>Py_CLEAR</code>.</li>
</ul>
<p><strong>Compatibility notes</strong></p>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/giampaolo/psutil/commit/9eea97dd6f1d16ea33f5144c8925f1ce7a0688e1"><code>9eea97d</code></a>
Pre-release</li>
<li><a
href="https://github.com/giampaolo/psutil/commit/938ac647418f09e4e610b2c755741316713c5592"><code>938ac64</code></a>
Rm sphinxcontrib.googleanalytics; override layout.html</li>
<li><a
href="https://github.com/giampaolo/psutil/commit/9dcbb7e60e650f0ab0cb52154b0a12c70f6a1e4c"><code>9dcbb7e</code></a>
Add sphinxcontrib-googleanalytics to requirements.txt</li>
<li><a
href="https://github.com/giampaolo/psutil/commit/76eaf9ae0f2868569c14b46f4165310885a40a15"><code>76eaf9a</code></a>
Try to add google analytics to doc</li>
<li><a
href="https://github.com/giampaolo/psutil/commit/de1cafa56f54e97ca557993155e76dd98877e136"><code>de1cafa</code></a>
Update doc mentioning Process.wait() internal details</li>
<li><a
href="https://github.com/giampaolo/psutil/commit/bb30943b0336a16f28437ec549c15a8ad2830cca"><code>bb30943</code></a>
Refact can_use_pidfd_open() and can_use_kqueue()</li>
<li><a
href="https://github.com/giampaolo/psutil/commit/a571717d6520d436273c8cb34ca871db4bfa508a"><code>a571717</code></a>
<a
href="https://redirect.github.com/giampaolo/psutil/issues/2708">#2708</a>,
macos / cmdline / environ; raise AD instead of OSError(0) (<a
href="https://redirect.github.com/giampaolo/psutil/issues/2709">#2709</a>)</li>
<li><a
href="https://github.com/giampaolo/psutil/commit/8b98c3effc20dcc4ed08c8f3d33e11ec0f5445b1"><code>8b98c3e</code></a>
Pre-release</li>
<li><a
href="https://github.com/giampaolo/psutil/commit/700b7e6a4171ae7c775679217205f1d97568ae00"><code>700b7e6</code></a>
[macOS] fix potential leaks in error paths (<a
href="https://redirect.github.com/giampaolo/psutil/issues/2707">#2707</a>)</li>
<li><a
href="https://github.com/giampaolo/psutil/commit/7cc7923a1479fb1d32bb25d3e78b465e2695fbf7"><code>7cc7923</code></a>
Windows / cmdline(): be more defensive in free()ing in case of
error</li>
<li>Additional commits viewable in <a
href="https://github.com/giampaolo/psutil/compare/v6.1.0...v7.2.2">compare
view</a></li>
</ul>
</details>
<br />


Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
Co-authored-by: Cheurteenyt <cheurteen@tuta.io>